# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

jaccard_coeff <- function(idx) {
    .Call('cytofkit_jaccard_coeff', PACKAGE = 'cytofkit', idx)
}

